export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  FAQ: '/faq',
  CONTACT: '/contact',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_OTP: '/verify-otp',
  FORGOT_PASSWORD: '/forgot-password',
  ADMIN_LOGIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  SUPER_ADMIN_LOGIN: '/sadmin',
  SUPER_ADMIN_DASHBOARD: '/sadmin/dashboard',
  STUDENT_DASHBOARD: '/dashboard',
  STUDENT_RESUME: '/dashboard/resume',
  STUDENT_CV: '/dashboard/cv',
  STUDENT_COVER_LETTER: '/dashboard/cover-letter',
  STUDENT_ATS: '/dashboard/ats-checker',
  STUDENT_MOCK_INTERVIEW: '/dashboard/mock-interview',
  STUDENT_INTERNSHIPS: '/dashboard/internships',
  STUDENT_WORKSHOPS: '/dashboard/workshops',
  STUDENT_SKILLS: '/dashboard/skills',
  STUDENT_PROJECTS: '/dashboard/projects',
  STUDENT_PROFILE: '/dashboard/profile'
};
